version: "3"

services:
  backend:
    build:
      context: .
    container_name: sharesapp_container
    depends_on:
      - db
    environment:
      POSTGRES_DB_URL: postgresql://db:5432/sharesapp
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: mypostgres13
      POSTGRES_USER: postgres
      POSTGRES_DB: sharesapp
    ports:
      - 5432:5432
    volumes:
      - C:/BSUIR/PiHLL/2_sem/postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../frontend/sharesapp-frontend
    container_name: frontend_container
    ports:
      - 5173:5173
